# replica set require selector
# selector help replica set to identify what pod fall under it
## if there are so many pods the replica can query pods by label to know and manage
# cause replica set can also manage pods that were not created as part of the replica set section
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
