apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-depoyment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: myapp-container
          image: nginx:1.28
  replicas: 3
  selector:
    matchLabels:
      app: myapp
