apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  ports:
    - name: result-service
      port: 8081
      targetPort: 80
      nodePort: 30002
  selector:
    app: result
